name: auto_pr

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
jobs:
  create_merge_pr:
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.merge_request.outputs.pull-request-number }}
      branch: ${{ steps.merge_request.outputs.pull-request-branch  }}
    steps:
      - name: current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: auto-pr-branch
      - name: switch to main HEAD
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Merge Pull Request
        id: merge_request
        uses: peter-evans/create-pull-request@v7
        with:
          title: pr (${{ steps.date.outputs.date }})
          branch: "update/${{ steps.date.outputs.date }}"
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          body: |
            This is an auto-generated PR.
            main -> auto-pr-branch
  check_branch_name:
    runs-on: ubuntu-latest
    needs: [create_merge_pr]
    steps:
      - name: Check branch name
        run: |
          echo "branch name: ${{ needs.create_merge_pr.outputs.branch }}"
  workflow1:
    needs: [create_merge_pr]
    uses: ./.github/workflows/workflow1.yml
    with:
      target_branch: ${{ needs.create_merge_pr.outputs.branch }}

  workflow2:
    needs: [create_merge_pr]
    uses: ./.github/workflows/workflow2.yml
    with:
      target_branch: ${{ needs.create_merge_pr.outputs.branch }}

  workflow3:
    needs: [create_merge_pr]
    uses: ./.github/workflows/workflow3.yml
    with:
      target_branch: ${{ needs.create_merge_pr.outputs.branch }}

  apply_mergeable_label:
    runs-on: ubuntu-latest
    needs: [create_merge_pr, workflow1, workflow2, workflow3]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add success label
        if: >-
          needs.workflow1.result == 'success' && needs.workflow2.result == 'success' && needs.workflow3.result == 'success'
        run: gh pr edit ${{ needs.create_merge_pr.outputs.pull-request-number }} --add-label auto-mergeable
      - name: Add failed label
        if: >-
          needs.workflow1.result == 'failure' || needs.workflow2.result == 'failure' || needs.workflow3.result == 'failure'
        run: gh pr edit ${{ needs.create_merge_pr.outputs.pull-request-number }} --add-label ci-failed
