name: auto_pr_approver

on:
  pull_request:
    types: [labeled]
    branches:
      - auto-update/auto-pr-branch-*
  workflow_dispatch:

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >-
      github.event.label.name == 'ci-passed' &&
      github.event.pull_request.user.login == 'github-actions[bot]'
    steps:
      - name: Review
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
